name = "StressStrain"
uuid = "35c0c9d5-9623-45a6-a87f-5a655e412bc9"
authors = ["Werner Zanzinger <werner.zanzinger@gmail.com>"]
version = "0.1.0"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DataInterpolations = "8.6.1"
DelimitedFiles = "1.9.1"
Optim = "1.13.2"
StaticArrays = "1.9.15"
