name = "StressStrain"
uuid = "35c0c9d5-9623-45a6-a87f-5a655e412bc9"
authors = ["Werner Zanzinger <werner.zanzinger@gmail.com>"]
version = "0.2.0"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
RegularizationTools = "29dad682-9a27-4bc3-9c72-016788665182"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DataInterpolations = "8.6.1"
DelimitedFiles = "1.9.1"
GLMakie = "0.13.6"
LinearAlgebra = "1.11.0"
Observables = "0.5.5"
Optim = "1.13.2"
RegularizationTools = "0.6.0"
StaticArrays = "1.9.15"
